// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "Structs/Player/ProtoGetPlayerRequest.h"
#include "Structs/Player/ProtoGetPlayerResponse.h"

#include "ProtoPlayerService.generated.h"

class URavenGrpcClientSubsystem;

// ─────────────────────────────────────────────────────────────────────────────
// Per-RPC completion callbacks
// ─────────────────────────────────────────────────────────────────────────────

using FOnGetPlayerComplete = TFunction<void(FProtoGetPlayerResponse, bool /*bSuccess*/)>;

// Blueprint-friendly dynamic delegate counterparts (used by Blueprint-callable RPC overloads)
DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnGetPlayerCompleteDynamic, FProtoGetPlayerResponse, Response, bool, bSuccess);

/**
 * UProtoPlayerService
 *
 * Static helpers grouping all PlayerService RPCs.
 * Every method dispatches through the supplied URavenGrpcClientSubsystem::SendRequest transport.
 *
 * Route pattern: {BaseURL}/player.PlayerService/{MethodName}
 */
UCLASS()
class EXAMPLEGRPCCLIENT_API UProtoPlayerService : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	// ── PlayerService RPCs ────────────────────────────────────────────────

	/** Corresponds to PlayerService.GetPlayer (C++ TFunction callback). */
	static void GetPlayer(
		URavenGrpcClientSubsystem* Subsystem,
		const FProtoGetPlayerRequest& Request,
		FOnGetPlayerComplete OnComplete
	);

	/** Blueprint-callable overload of GetPlayer (uses a dynamic delegate). */
	UFUNCTION(BlueprintCallable, Category = "Proto|Player|PlayerService")
	static void GetPlayer(
		URavenGrpcClientSubsystem* Subsystem,
		const FProtoGetPlayerRequest& Request,
		FOnGetPlayerCompleteDynamic OnComplete
	);

};
