// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "PlayerRace.generated.h"

UENUM(BlueprintType)
enum class EPlayerRace : uint8
{
	Human = 0,
	Elf = 1,
	Dwarf = 2,
};

UCLASS()
class UPlayerRaceHelper : public UObject
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category = "Player Race")
	static FText GetPlayerRaceText(const EPlayerRace playerRace)
	{
		return UEnum::GetDisplayValueAsText(playerRace);
	}

	UFUNCTION(BlueprintPure, Category = "Player Race")
	static FString GetPlayerRaceString(const EPlayerRace playerRace)
	{
		return GetPlayerRaceText(playerRace).ToString();
	}
};
