// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "PlayerClass.generated.h"

UENUM(BlueprintType)
enum class EPlayerClass : uint8
{
	Warrior = 0,
	Priest = 1,
	Mage = 2,
};

UCLASS()
class UPlayerClassHelper : public UObject
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category = "Player Class")
	static FText GetPlayerClassText(const EPlayerClass playerClass)
	{
		return UEnum::GetDisplayValueAsText(playerClass);
	}

	UFUNCTION(BlueprintPure, Category = "Player Class")
	static FString GetPlayerClassString(const EPlayerClass playerClass)
	{
		return GetPlayerClassText(playerClass).ToString();
	}
};
