// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "Enums/PlayerClass.h"
#include "Enums/PlayerRace.h"
#include "ProtoPlayer.generated.h"

/** Mirrors player.Player */
USTRUCT(BlueprintType)
struct EXAMPLEGRPCCLIENT_API FProtoPlayer
{
	GENERATED_BODY()
	
	/** player_id  [field 1] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	int64 PlayerId = 0;

	/** name  [field 2] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	FString Name;

	/** title  [field 3] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	FString Title;

	/** player_race  [field 4] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	EPlayerRace PlayerRace = EPlayerRace::Human;

	/** player_class  [field 5] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	EPlayerClass PlayerClass = EPlayerClass::Warrior;

	/** level  [field 6] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	int32 Level = 0;

	/** xp  [field 7] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	int32 Xp = 0;

	/** sp  [field 8] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	int32 Sp = 0;

public:
	// ── Codec ──────────────────────────────────────────────────────────────────

	/** Encode to protobuf binary wire format. */
	TArray<uint8> Encode() const;

	/** Decode from a TArray byte buffer. */
	static bool Decode(const TArray<uint8>& Data, FProtoPlayer& Out);

	/** Decode from a raw pointer + length (used for embedded messages). */
	static bool Decode(const uint8* Data, int32 Length, FProtoPlayer& Out);

	// ── Debug ──────────────────────────────────────────────────────────────────

	/** Returns a human-readable debug string of the struct contents. */
	FString ToString() const;
};
