// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "Structs/Player/ProtoPlayer.h"
#include "ProtoGetPlayerResponse.generated.h"

/** Mirrors player.GetPlayerResponse */
USTRUCT(BlueprintType)
struct EXAMPLEGRPCCLIENT_API FProtoGetPlayerResponse
{
	GENERATED_BODY()
	
public:
	/** player  [field 1] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	FProtoPlayer Player;

public:
	// ── Codec ──────────────────────────────────────────────────────────────────

	/** Encode to protobuf binary wire format. */
	TArray<uint8> Encode() const;

	/** Decode from a TArray byte buffer. */
	static bool Decode(const TArray<uint8>& Data, FProtoGetPlayerResponse& Out);

	// ── Debug ──────────────────────────────────────────────────────────────────

	/** Returns a human-readable debug string of the struct contents. */
	FString ToString() const;
};
