// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "ProtoGetPlayerRequest.generated.h"

/** Mirrors player.GetPlayerRequest */
USTRUCT(BlueprintType)
struct EXAMPLEGRPCCLIENT_API FProtoGetPlayerRequest
{
	GENERATED_BODY()
	
public:
	/** player_id  [field 1] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|Player")
	int32 PlayerId = 0;

public:
	// ── Codec ──────────────────────────────────────────────────────────────────

	/** Encode to protobuf binary wire format. */
	TArray<uint8> Encode() const;

	// ── Debug ──────────────────────────────────────────────────────────────────

	/** Returns a human-readable debug string of the struct contents. */
	FString ToString() const;
};
