// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "Structs/World/ProtoGetMyWorldRequest.h"
#include "Structs/World/ProtoGetMyWorldResponse.h"

#include "ProtoWorldService.generated.h"

class URavenGrpcClientSubsystem;

// ─────────────────────────────────────────────────────────────────────────────
// Per-RPC completion callbacks
// ─────────────────────────────────────────────────────────────────────────────

using FOnGetMyWorldComplete = TFunction<void(FProtoGetMyWorldResponse, bool /*bSuccess*/)>;

// Blueprint-friendly dynamic delegate counterparts (used by Blueprint-callable RPC overloads)
DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnGetMyWorldCompleteDynamic, FProtoGetMyWorldResponse, Response, bool, bSuccess);

/**
 * UProtoWorldService
 *
 * Static helpers grouping all WorldService RPCs.
 * Every method dispatches through the supplied URavenGrpcClientSubsystem::SendRequest transport.
 *
 * Route pattern: {BaseURL}/world.WorldService/{MethodName}
 */
UCLASS()
class EXAMPLEGRPCCLIENT_API UProtoWorldService : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	// ── WorldService RPCs ─────────────────────────────────────────────────

	/** Corresponds to WorldService.GetMyWorld (C++ TFunction callback). */
	static void GetMyWorld(
		URavenGrpcClientSubsystem* Subsystem,
		const FProtoGetMyWorldRequest& Request,
		FOnGetMyWorldComplete OnComplete
	);

	/** Blueprint-callable overload of GetMyWorld (uses a dynamic delegate). */
	UFUNCTION(BlueprintCallable, Category = "Proto|World|WorldService")
	static void GetMyWorld(
		URavenGrpcClientSubsystem* Subsystem,
		const FProtoGetMyWorldRequest& Request,
		FOnGetMyWorldCompleteDynamic OnComplete
	);

};
