// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Services/Player/ProtoPlayerService.h"
#include "GameInstance/RavenGrpcClientSubsystem.h"

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

static const FString PlayerServiceBase = TEXT("player.PlayerService");

// ─────────────────────────────────────────────────────────────────────────────
// UProtoPlayerService
// ─────────────────────────────────────────────────────────────────────────────

void UProtoPlayerService::GetPlayer(
	URavenGrpcClientSubsystem* Subsystem,
	const FProtoGetPlayerRequest& Request,
	FOnGetPlayerComplete OnComplete
)
{
	if (!Subsystem) { return; }

	Subsystem->SendRequest<FProtoGetPlayerRequest, FProtoGetPlayerResponse>(
		FString::Printf(TEXT("%s/GetPlayer"), *PlayerServiceBase),
		Request,
		MoveTemp(OnComplete)
	);
}

void UProtoPlayerService::GetPlayer(
	URavenGrpcClientSubsystem* Subsystem,
	const FProtoGetPlayerRequest& Request,
	FOnGetPlayerCompleteDynamic OnComplete
)
{
	GetPlayer(
		Subsystem,
		Request,
		[OnComplete](const FProtoGetPlayerResponse& Response, bool bSuccess)
		{
			OnComplete.ExecuteIfBound(Response, bSuccess);
		}
	);
}
