// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "ProtoWorldStatus.generated.h"

/** Mirrors world.WorldStatus */
USTRUCT(BlueprintType)
struct EXAMPLEGRPCCLIENT_API FProtoWorldStatus
{
	GENERATED_BODY()
	
	/** world_id  [field 1] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|World")
	int64 WorldId = 0;

	/** name  [field 2] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|World")
	FString Name;

	/** time  [field 3] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|World")
	FString Time;

public:
	// ── Codec ──────────────────────────────────────────────────────────────────

	/** Encode to protobuf binary wire format. */
	TArray<uint8> Encode() const;

	/** Decode from a TArray byte buffer. */
	static bool Decode(const TArray<uint8>& Data, FProtoWorldStatus& Out);

	/** Decode from a raw pointer + length (used for embedded messages). */
	static bool Decode(const uint8* Data, int32 Length, FProtoWorldStatus& Out);

	// ── Debug ──────────────────────────────────────────────────────────────────

	/** Returns a human-readable debug string of the struct contents. */
	FString ToString() const;
};
