// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#pragma once

#include "CoreMinimal.h"
#include "ProtoGetMyWorldRequest.generated.h"

/** Mirrors world.GetMyWorldRequest */
USTRUCT(BlueprintType)
struct EXAMPLEGRPCCLIENT_API FProtoGetMyWorldRequest
{
	GENERATED_BODY()
	
public:
	/** world_id  [field 1] */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Proto|World")
	int32 WorldId = 0;

public:
	// ── Codec ──────────────────────────────────────────────────────────────────

	/** Encode to protobuf binary wire format. */
	TArray<uint8> Encode() const;

	// ── Debug ──────────────────────────────────────────────────────────────────

	/** Returns a human-readable debug string of the struct contents. */
	FString ToString() const;
};
