// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Services/World/ProtoWorldService.h"
#include "GameInstance/RavenGrpcClientSubsystem.h"

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

static const FString WorldServiceBase = TEXT("world.WorldService");

// ─────────────────────────────────────────────────────────────────────────────
// UProtoWorldService
// ─────────────────────────────────────────────────────────────────────────────

void UProtoWorldService::GetMyWorld(
	URavenGrpcClientSubsystem* Subsystem,
	const FProtoGetMyWorldRequest& Request,
	FOnGetMyWorldComplete OnComplete
)
{
	if (!Subsystem) { return; }

	Subsystem->SendRequest<FProtoGetMyWorldRequest, FProtoGetMyWorldResponse>(
		FString::Printf(TEXT("%s/GetMyWorld"), *WorldServiceBase),
		Request,
		MoveTemp(OnComplete)
	);
}

void UProtoWorldService::GetMyWorld(
	URavenGrpcClientSubsystem* Subsystem,
	const FProtoGetMyWorldRequest& Request,
	FOnGetMyWorldCompleteDynamic OnComplete
)
{
	GetMyWorld(
		Subsystem,
		Request,
		[OnComplete](const FProtoGetMyWorldResponse& Response, bool bSuccess)
		{
			OnComplete.ExecuteIfBound(Response, bSuccess);
		}
	);
}
