// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/World/ProtoGetMyWorldRequest.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoGetMyWorldRequest::Encode() const
{
	FProtoWireWriter W;
	W.WriteInt32(1, WorldId); // world_id
	return W.Finish();
}

FString FProtoGetMyWorldRequest::ToString() const
{
	FString Result = TEXT("FProtoGetMyWorldRequest { ");
	Result += FString::Printf(TEXT("WorldId=%d"), WorldId);
	Result += TEXT(" }");
	return Result;
}
