// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/World/ProtoWorldStatus.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoWorldStatus::Encode() const
{
	FProtoWireWriter W;
	W.WriteInt64 (1, WorldId); // world_id
	W.WriteString(2, Name);    // name
	W.WriteString(3, Time);    // time
	return W.Finish();
}

bool FProtoWorldStatus::Decode(const uint8* Data, int32 Length, FProtoWorldStatus& Out)
{
	FProtoWireReader R(Data, Length);
	while (!R.IsAtEnd())
	{
		uint32 Field, Wire;
		if (!R.ReadTag(Field, Wire)) break;

		switch (Field)
		{
		case 1: R.ReadInt64(Out.WorldId); break; // world_id
		case 2: R.ReadString(Out.Name);   break; // name
		case 3: R.ReadString(Out.Time);   break; // time
		default: R.SkipField(Wire);        break;
		}
	}
	return true;
}

bool FProtoWorldStatus::Decode(const TArray<uint8>& Data, FProtoWorldStatus& Out)
{
	return Decode(Data.GetData(), Data.Num(), Out);
}

FString FProtoWorldStatus::ToString() const
{
	FString Result = TEXT("FProtoWorldStatus { ");
	Result += FString::Printf(TEXT("WorldId=%lld, "), WorldId);
	Result += FString::Printf(TEXT("Name=\"%s\", "), *Name);
	Result += FString::Printf(TEXT("Time=\"%s\""), *Time);
	Result += TEXT(" }");
	return Result;
}
