// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/World/ProtoGetMyWorldResponse.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoGetMyWorldResponse::Encode() const
{
	FProtoWireWriter W;
	W.WriteMessage(1, WorldStatus.Encode()); // world_status
	return W.Finish();
}

bool FProtoGetMyWorldResponse::Decode(const TArray<uint8>& Data, FProtoGetMyWorldResponse& Out)
{
	FProtoWireReader R(Data);
	while (!R.IsAtEnd())
	{
		uint32 Field, Wire;
		if (!R.ReadTag(Field, Wire)) break;

		if (Field == 1) // world_status
		{
			const uint8* SubData = nullptr;
			int32        SubLen  = 0;
			if (R.ReadMessageBytes(SubData, SubLen))
			{
				FProtoWorldStatus::Decode(SubData, SubLen, Out.WorldStatus);
			}
		}
		else
		{
			R.SkipField(Wire);
		}
	}
	return true;
}

FString FProtoGetMyWorldResponse::ToString() const
{
	FString Result = TEXT("FProtoGetMyWorldResponse { ");
	Result += FString::Printf(TEXT("WorldStatus=%s"), *WorldStatus.ToString());
	Result += TEXT(" }");
	return Result;
}
