// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/Player/ProtoGetPlayerRequest.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoGetPlayerRequest::Encode() const
{
	FProtoWireWriter W;
	W.WriteInt32(1, PlayerId); // player_id
	return W.Finish();
}

FString FProtoGetPlayerRequest::ToString() const
{
	FString Result = TEXT("FProtoGetPlayerRequest { ");
	Result += FString::Printf(TEXT("PlayerId=%d"), PlayerId);
	Result += TEXT(" }");
	return Result;
}
