// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/Player/ProtoPlayer.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoPlayer::Encode() const
{
	FProtoWireWriter W;
	W.WriteInt64 (1, PlayerId);                        // player_id
	W.WriteString(2, Name);                            // name
	W.WriteString(3, Title);                           // title
	W.WriteInt32 (4, static_cast<int32>(PlayerRace));  // player_race
	W.WriteInt32 (5, static_cast<int32>(PlayerClass)); // player_class
	W.WriteInt32 (6, Level);                           // level
	W.WriteInt32 (7, Xp);                              // xp
	W.WriteInt32 (8, Sp);                              // sp
	return W.Finish();
}

bool FProtoPlayer::Decode(const uint8* Data, int32 Length, FProtoPlayer& Out)
{
	FProtoWireReader R(Data, Length);
	while (!R.IsAtEnd())
	{
		uint32 Field, Wire;
		if (!R.ReadTag(Field, Wire)) break;

		if (Field == 1) // player_id
		{
			R.ReadInt64(Out.PlayerId);
		}
		else if (Field == 2) // name
		{
			R.ReadString(Out.Name);
		}
		else if (Field == 3) // title
		{
			R.ReadString(Out.Title);
		}
		else if (Field == 4) // player_race
		{
			int32 PlayerRaceRaw = 0;
			R.ReadInt32(PlayerRaceRaw);
			Out.PlayerRace = static_cast<EPlayerRace>(PlayerRaceRaw);
		}
		else if (Field == 5) // player_class
		{
			int32 PlayerClassRaw = 0;
			R.ReadInt32(PlayerClassRaw);
			Out.PlayerClass = static_cast<EPlayerClass>(PlayerClassRaw);
		}
		else if (Field == 6) // level
		{
			R.ReadInt32(Out.Level);
		}
		else if (Field == 7) // xp
		{
			R.ReadInt32(Out.Xp);
		}
		else if (Field == 8) // sp
		{
			R.ReadInt32(Out.Sp);
		}
		else
		{
			R.SkipField(Wire);
		}
	}
	return true;
}

bool FProtoPlayer::Decode(const TArray<uint8>& Data, FProtoPlayer& Out)
{
	return Decode(Data.GetData(), Data.Num(), Out);
}

FString FProtoPlayer::ToString() const
{
	FString Result = TEXT("FProtoPlayer { ");
	Result += FString::Printf(TEXT("PlayerId=%lld, "), PlayerId);
	Result += FString::Printf(TEXT("Name=\"%s\", "), *Name);
	Result += FString::Printf(TEXT("Title=\"%s\", "), *Title);
	Result += FString::Printf(TEXT("PlayerRace=%s, "), *UPlayerRaceHelper::GetPlayerRaceString(PlayerRace));
	Result += FString::Printf(TEXT("PlayerClass=%s, "), *UPlayerClassHelper::GetPlayerClassString(PlayerClass));
	Result += FString::Printf(TEXT("Level=%d, "), Level);
	Result += FString::Printf(TEXT("Xp=%d, "), Xp);
	Result += FString::Printf(TEXT("Sp=%d"), Sp);
	Result += TEXT(" }");
	return Result;
}
