// Licensed to RavenGRPC. All rights reserved.
// <auto-generated> This file was generated by RavenGRPC. Do not edit by hand.

#include "Structs/Player/ProtoGetPlayerResponse.h"
#include "Proto/RavenProtoCommonCodec.h"

TArray<uint8> FProtoGetPlayerResponse::Encode() const
{
	FProtoWireWriter W;
	W.WriteMessage(1, Player.Encode()); // player
	return W.Finish();
}

bool FProtoGetPlayerResponse::Decode(const TArray<uint8>& Data, FProtoGetPlayerResponse& Out)
{
	FProtoWireReader R(Data);
	while (!R.IsAtEnd())
	{
		uint32 Field, Wire;
		if (!R.ReadTag(Field, Wire)) break;

		if (Field == 1) // player
		{
			const uint8* SubData = nullptr;
			int32        SubLen  = 0;
			if (R.ReadMessageBytes(SubData, SubLen))
			{
				FProtoPlayer::Decode(SubData, SubLen, Out.Player);
			}
		}
		else
		{
			R.SkipField(Wire);
		}
	}
	return true;
}

FString FProtoGetPlayerResponse::ToString() const
{
	FString Result = TEXT("FProtoGetPlayerResponse { ");
	Result += FString::Printf(TEXT("Player=%s"), *Player.ToString());
	Result += TEXT(" }");
	return Result;
}
